### PR TITLE
Bug fixes/notes

### PR DESCRIPTION
**Pull request by lmkz**
Used your project to import my old Thunderbird emails. Just had to fix a couple of wee bugs first.

### CODE REVIEW

**Comment by RobbieLD** [comment]
Thanks very much for the PR. What bit doesn't work in other browsers aside from FireFox? I haven't run this app in a long time but I've still got some files generated by it which still seem to work in Chrome. The DOM loaded event still shows as supported: https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

**Comment by lmkz** [comment]
Ah yeah I just tried it again and it does work now, maybe it's because it didn't load bulma initially, I pointed it to a cdn, then fixed the bug after that, maybe it had a cached newer version. I just assumed it was some iframe thing. But yes happy to roll that bit back. I think still a very useful tool when you need to dredge up a 15 year old email thanks!

**Comment by RobbieLD** [comment]
Ah cool thanks for checking. I was a bit confused about what could have broken but yeah it probably that bulma hadn't loaded. Glad you found it useful. It was just something I wrote for exactly the purpose your described. Parsing a giant old email file. Anyway if you remove that firefox warning I'll merge the PR.

**Comment by lmkz** [comment]
Will alter and create a new one

**Pull request closed without merging**
